import Vue from 'vue'
import { Button, Cascader, Tree, Select, Option, MessageBox, Tag, Dialog, Pagination, Table, Tooltip, Switch, TableColumn, Form, FormItem, Col, Row, Input, Card, Message, Container, Header, Aside, Main, Menu, Submenu, MenuItem, Breadcrumb, BreadcrumbItem } from 'element-ui'
Vue.use(Button)
Vue.use(Cascader)
Vue.use(Select)
Vue.use(Option)
Vue.use(Pagination)
Vue.use(Tree)
Vue.use(Tag)
Vue.use(Dialog)
Vue.use(Tooltip)
Vue.use(Switch)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Container)
Vue.use(Header)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(MenuItem)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Card)
Vue.use(Col)
Vue.use(Row)
// 进行全局挂载：
Vue.prototype.$message = Message
Vue.prototype.$confirm = MessageBox.confirm
